version: 2
updates:
  - package-ecosystem: "npm" 
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    ignore:
      - dependency-name: "lucide-vue-next"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
