name: Auto Assign Reviewers

on:
  pull_request_target:
    types: [ opened, ready_for_review ]

jobs:
  assign:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Auto Assign Reviewers for Pull Requests
        uses: kentaro-m/auto-assign-action@2.0.0
        with:
          configuration-path: .github/auto_assign.yml