name: Auto Assign Reviewers

on:
  pull_request_target:
    types: [ opened, ready_for_review ]

jobs:
  assign:
    runs-on: ubuntu-latest
    steps:
      - uses: kentaro-m/auto-assign-action@2.0.0
        with:
          configuration-path: .github/auto_assign.yml